name: GemstonePowerups
version: 1.0.0
main: org.gemstones.GemstonePowerupsPlugin
description: A Minecraft plugin for giving players buffs/effects when in proximity to specific gemstone blocks.
author: RenTrieu
api-version: '1.20'
